### ISSUE TITLE
add an option to skip archive.org 

### ISSUE THREAD

**Issue by molitona** [xnl-h4ck3r/waymore#10]
Hi, many times a problem occurs when fetching from archive.org when the target is big like vimeo.com and waymore can't continue checking otx,cc and urlscan. Can you add an option to skip archive.org ?

**Comment by xnl-h4ck3r** [comment]
Hi @molitona 
What problems are you getting exactly? When I try vimeo.com it says it needs to get 7679 requests. That's obviously going to take quite a while, but is it actually failing? Are you running with `-v`, and what error messages are you seeing?
I always saw the links from archive.org as the main result set, and the others get additional links if there are any. I will look into adding an option to skip archive.org too though.
Regards
Xnl

**Comment by xnl-h4ck3r** [comment]
Hi @molitona 
I just ran for `vimeo.com` and I eventually run out of resources on my machine, but it found 52,281,029 links from archive.org before it ended. However, when I ran without archive.org, although it completed fully, it only found 640,817 links in total from the other 3 sources. 
So running waymore does need a lot of resources at the moment, and is probably best run on a VPS with a decent amount of RAM.
Regards
Xnl

**Comment by molitona** [comment]
> Hi @molitona I just ran for `vimeo.com` and I eventually run out of resources on my machine, but it found 52,281,029 links from archive.org before it ended. However, when I ran without archive.org, although it completed fully, it only found 640,817 links in total from the other 3 sources. So running waymore does need a lot of resources at the moment, and is probably best run on a VPS with a decent amount of RAM. Regards Xnl

Hi @xnl-h4ck3r,
i have cpu and ram available when  running it. it doesn't fail for luck of resources for me. My CPU&RAM is way less than 100% when it's being used.

**Comment by xnl-h4ck3r** [comment]
Hi @molitona 
Can you get the latest version and try running again? Can you also run with `-v` and let me know specififc errors you are getting?
Thanks
Xnl

**Comment by xnl-h4ck3r** [comment]
Hi @molitona 
There is now an argument `-xwm` in v1.7 to skip archive.org when searching for links.
Thansk for the suggestion and using the tool!
Kind egards
Xnl
