### ISSUE TITLE
error release v1.5

### ISSUE THREAD

**Issue by GH846** [xnl-h4ck3r/waymore#11]
Hi,

great tool !!!

after installing v1.5 get this error:

Traceback (most recent call last):
  File "waymore.py", line 9, in <module>
    from tkinter import EXCEPTION
ModuleNotFoundError: No module named 'tkinter'

Kind regards

**Comment by 4riful** [comment]
same problem , then I have installed tkinter by pip3 install tk 
but it threw me same error ,
kindly fix it 

thanks

**Comment by GH846** [comment]
Working fine now... thanks for quick fix ;-)
