### ISSUE TITLE
Problem when running command from a symlink in linux

### ISSUE THREAD

**Issue by Devang-Solanki** [xnl-h4ck3r/waymore#16]
The Shebang line contains some dos character that throw error when running it as standalone file without python3 command.

![image](https://user-images.githubusercontent.com/75718583/193829054-b72dad07-c2ac-44d8-9de3-92f3bed8f8d6.png)

This can easily be fixed with dos2unix command on Linux.

**Comment by xnl-h4ck3r** [comment]
Hi @Devang-Solanki 
This should have been fixed in the latest version of waymore now. Can you try it out and let me know if it is because I can't reproduce the error myself.
Many thanks
Xnl

**Comment by Devang-Solanki** [comment]
Hi @xnl-h4ck3r,

This is fixed now.
