### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Teicu** [xnl-h4ck3r/waymore#17]
Hi, 

Just a question. Is there a command to extract only URLs with parameters?  

Thanks

**Comment by xnl-h4ck3r** [comment]
Hi @Teicu 
Thanks for taking the time to use the tool and for asking the question!
You could use `-ra '\?[^$]` so it filters the output to links have a `?` followed by any other character, i.e. has a query string.
Let me know if that solves the issue.
Kind regards
Xnl

**Comment by Teicu** [comment]
Thank you very much

**Comment by Teicu** [comment]
Hi @xnl-h4ck3r  

Thank you again for this tool. it is wonderful. I'd like to ask you one more question. Is there a possibility to save only url addresses with the answer 200? and what would be the command to use? Thanks

**Comment by xnl-h4ck3r** [comment]
Hi @Teicu 
There isn't a command directly at the moment, but in the config file there is a default value of `FILTER_CODE: 404,301,302` which means it will only download responses with codes that are NOT 404,301,302. So, you could change that and add all the usual response codes apart from 200? I'll look into making that better.
This only applies to Wayback Machine and Common Crawl though. URLScan and Alien Vault APIs don't have the option to filter on response code unfortnately, but if you wanted to exclude those sources, you can use -xav and -xus
Thanks
Xnl

**Comment by xnl-h4ck3r** [comment]
Sorry, I was wrong about the URLScan and Alien Vault APIs.... they do get checked with the same Status Codes too
