### ISSUE TITLE
error: Couldn't find a setup script in /tmp/easy_install-9FgCfj/termcolor-2.1.1.tar.gz

### ISSUE THREAD

**Issue by Prajwal-PS7** [xnl-h4ck3r/waymore#18]
while running this cmd "$ **sudo python setup.py install**"
-----------------------------------------------------------------------------

Output :>>

running install
running bdist_egg
running egg_info
writing requirements to waymore.egg-info/requires.txt
writing waymore.egg-info/PKG-INFO
writing top-level names to waymore.egg-info/top_level.txt
writing dependency_links to waymore.egg-info/dependency_links.txt
reading manifest file 'waymore.egg-info/SOURCES.txt'
writing manifest file 'waymore.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/waymore
copying build/lib.linux-x86_64-2.7/waymore/__init__.py -> build/bdist.linux-x86_64/egg/waymore
copying build/lib.linux-x86_64-2.7/waymore.py -> build/bdist.linux-x86_64/egg
byte-compiling build/bdist.linux-x86_64/egg/waymore/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/waymore.py to waymore.pyc
  File "build/bdist.linux-x86_64/egg/waymore.py", line 147
    return f"{size:.{decimal_places}f} {unit}"
                                             ^
SyntaxError: invalid syntax

creating build/bdist.linux-x86_64/egg/EGG-INFO
copying waymore.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying waymore.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying waymore.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying waymore.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying waymore.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/waymore-1.11-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing waymore-1.11-py2.7.egg
Removing /usr/local/lib/python2.7/dist-packages/waymore-1.11-py2.7.egg
Copying waymore-1.11-py2.7.egg to /usr/local/lib/python2.7/dist-packages
waymore 1.11 is already the active version in easy-install.pth

Installed /usr/local/lib/python2.7/dist-packages/waymore-1.11-py2.7.egg
Processing dependencies for waymore==1.11
Searching for termcolor
Reading https://pypi.org/simple/termcolor/
Downloading https://files.pythonhosted.org/packages/19/da/ff1f0906818a5bd2e69e773d88801ca3c9e92d0d7caa99db1665658819ea/termcolor-2.1.1.tar.gz#sha256=67cee2009adc6449c650f6bcf3bdeed00c8ba53a8cda5362733c53e0a39fb70b
Best match: termcolor 2.1.1
Processing termcolor-2.1.1.tar.gz
error: Couldn't find a setup script in /tmp/easy_install-9FgCfj/termcolor-2.1.1.tar.gz

-----------------------------------------------------------------------------
I tried to add this file manually but not working.

**Comment by xnl-h4ck3r** [comment]
Hi @Prajwal-PS7 
Thanks for taking the time to raise an issue. I haven't come across that problem before. I'll take a look into it today.
Kind regards
Xnl

**Comment by xnl-h4ck3r** [comment]
HI @Prajwal-PS7 
Unfortunately I can't rerpodcue the problem myself. I'm wondering whether it's to do with Python versions on your machine. Can you try `sudo python3 setup.py install` instead and see if that makes a difference? 
Thanks
Xnl

**Comment by xnl-h4ck3r** [comment]
Hi @Prajwal-PS7, I haven't heard back from you... did you manage to get it working?
Regards
Xnl

**Comment by xnl-h4ck3r** [comment]
I haven't heard back so I'll close this issue. Thanks
