### ISSUE TITLE
Add an argument like -config

### ISSUE THREAD

**Issue by iamRjarpan** [xnl-h4ck3r/waymore#19]
Hi,
I want to say that is it possible to add a feature that allows to mension config.yaml path because sometime it can't find it the find because I run it with alias in bash_profile. So it will be very helpful if I can mension the file with an argument like 
```
python3 waymore.py -config /path/to/somewhere/far/config.yaml 
```
Here is the problem I faced. And it will possible to add same feature with xnLinkfinder too?
![Screenshot 2022-12-20 190748](https://user-images.githubusercontent.com/45498226/208680587-e27c1982-42ee-41dc-b118-598d487684ec.png)

**Comment by xnl-h4ck3r** [comment]
Hi @iamRjarpan, yes that's a good idea! I'll get that sorted soon, in waymore and xnLinkFinder, and let you know when it's there 
Many thanks
Xnl

**Comment by xnl-h4ck3r** [comment]
Hi @iamRjarpan, the new arguemnt `-c` / `--config` is available in v1.12 now. If you don't pass the full path of a config file (you need to include the file name), it will default to looking for `cponfig.yml` in the same dorectory as the runtime file `waymore.py`, as usual.
Thanks for taking the time to use the tool, and for suggesting the change
Xnl

**Comment by xnl-h4ck3r** [comment]
Hi @mohammed19990. Can you run `waymore --version` and check it is v4.6 (I'm not sure why I said v1.12 before!). If it isn't 4.6 can you please run `pip install --upgrade waymore`. The config is usually found in `~/.config/waymore/` now. 
If this doesn't resolve the problem, can you share the exact command you are using please with the output?

**Comment by reedA201** [comment]
it is v4.6 snd the tool show me that 
WARNING: Cannot find file "cponfig.yml", so using default values 
and the tool run  and show that


Getting links from Wayback Machine (archive.org) with one request (this can take a while for some domains)...
and still show that

**Comment by xnl-h4ck3r** [comment]
You keep saying it says `cponfig.yml` but that does not even appear in the code for v4.6. 
Please can you send me a screenshot of your terminal with the exact command that you are running and the output please to help me solve this issue? Thanks

**Comment by xnl-h4ck3r** [comment]
Hi. Sorry I was confused with different people pasting `cponfig.yml`, and thought it was a typo in an old version or something.
When you install waymore using `pip install waymore` it should create the `config.yml` usually in `~/.config/waymore`. I assume it did not create that  directory, or the config file in that directory for some reason.
If you manually create  `~/.config/waymore` with the config you want, or the default one in the repo, you shouldn't get that warning anymore. Thanks

**Comment by reedA201** [comment]
Sorry for this stupid question, but what is the use of this file, and if I create it, what do I put inside it?

**Comment by xnl-h4ck3r** [comment]
That is all explained in the README file

**Comment by reedA201** [comment]
Please can you give me one example of how to fill out the file so I can be informed?

**Comment by xnl-h4ck3r** [comment]
If I explained it all, I would just be repeating everything in the README document. Please read that and if you have any questions after that I'd be happy to answer them. The default values are fine for most things, but you should know what they are if you want to get the most out of the tool
