### ISSUE TITLE
Feature request, Add -output argument 

### ISSUE THREAD

**Issue by iamRjarpan** [xnl-h4ck3r/waymore#20]
Hi, 
I really love your work and how much you putting your effort to build this tool, you resolved privious issue with `-config` very fast and I really appriciate that. I want to know that is it possible if I can pass -output flag like xnLinkfinder where it will check if -mode U then save it has given name in file. But if -mode B or R passed then it will create a dir automaticly not in `waymore/result` but in current dir or user's mensionsed dir. 
For example :- 
```
python waymore.py -mode U -out test
test <- txt file

python waymore.py -mode B -out test 
test <- folder
  |- waymore.txt 
  |- index.txt
  |- 123.xnl 
  
// also it can spicify output dir like this
python waymore.py -mode U -out /far/from/home/dir
```
Again thank you for all your time and efforts you putting into it. Good work

**Comment by xnl-h4ck3r** [comment]
Hi @iamRjarpan. I have released v1.13 which should solve this issue for you. There is a new argument called `-oU` where you can specify the name of the URL link file (and the path too). There is also a new argument `-oR` where you can specify the directory path where the archived responses are output. Let me know if you have any problems
