### ISSUE TITLE
waymore work stop due to empty line 

### ISSUE THREAD

**Issue by StrglrX** [xnl-h4ck3r/waymore#21]
Hi ,
if the input contain just one empty line we get "Each line of the input file must contain a domain only (with no schema)...." error even all other lines well formed .

I hop you will fix this issue , because as you know it's comman to have empty lines from other recon tool output .

**Comment by xnl-h4ck3r** [comment]
Hi @StrglrX 
You are right, sorry about that! That has been fixed now if you get the newest version 1.19. Thanks for using the tool and taking the time to raise the issue!
