### ISSUE TITLE
error of waymore on resolved subdomains

### ISSUE THREAD

**Issue by Otaku95** [xnl-h4ck3r/waymore#23]
**I have this issue with waymore when I run it on the resolved subdomains of the target.**
root@ubuntu:~/tools/waymore# cat resolved-subs.txt  | python3 waymore.py
Each line of the input file must contain a domain only (with no schema) to search for all links, or a domain and path (with no schema) to just get archived response for that URL. Do not pass a query string or fragment in any lines. The first line that seems invalid is: extweb-LIM.host.tld
If you believe this is flagged in error, please raise an issue on Github :)

**Comment by xnl-h4ck3r** [comment]
Hi @Otaku95 
I have tested this again and it works ok for me. Can you share the first few lines of the resolved-subs.txt file so I can see it might be raising that error?
Thanks

**Comment by xnl-h4ck3r** [comment]
Hi @Otaku95. are you able to share that so I can look into the issue?
Thanks
Xnl

**Comment by Otaku95** [comment]
Hi @xnl-h4ck3r. sorry for being late. I checked your source code and found out what my problem was. I had a number of uppercase and invalid subdomains which resolved to private range IPs (i.e 10.0.0/8). so I removed them. now it works. Thank you Xnl.

**Comment by xnl-h4ck3r** [comment]
Thanks for letting me know! Are you able to give me or examples of invalid subdomains so I can handle the errors better?
Thanks

**Comment by Otaku95** [comment]
Sure. A part of my large resolved subdomains list which leads to this problem is here. some of them has capital letters in subs section, others resolved to private IP ranges and 3 of them has extra dot at the end of subdomain which happened in my subdomain discovery process and when I checked the file I understood my problem.
I had another problem when I was using this tool, which was the lack of resources on my VPS. I execute your tool on the main domain (dell.com) and after one hours, the process was killed.

[abidr09.us.dell.com
81sw-i29.us.dell.com
abi10.us.dell.com
academy-apm-pc1.dell.com
abidr08.us.dell.com
ac05cmsha.us.dell.com
aacgsi2db-cname.us.dell.com
abi12.us.dell.com
abhays.us.dell.com
accessories-ux-p20.ux.dell.com
access-ebi.us.dell.com
account-svc-p61svc.dell.com
academy.ins.dell.com
agileatlas.us.dell.com
extweb-LIM.dell.com
support.euro.dell.com.
Password-emea.dell.com
83sw-b37.us.dell.com
53sw-b32.us.dell.com
22pstmnad0-okta-config.smtptest2.onetest.dell.com](url)

**Comment by xnl-h4ck3r** [comment]
Hi @Otaku95 
My apologies for such a long delay in resolving this. The issue with uppercase letters and domains ending in fullstops has been resolved in v1.22 now.
Thanks for using waymore and taking the time to raise an issue.
Regards
Xnl
