### ISSUE TITLE
The saved results are incorrect!!!

### ISSUE THREAD

**Issue by muxueo** [xnl-h4ck3r/waymore#26]
I use a "https://otx.alienvault.com/api/v1/indicators/domain/target.com/url_list?limit=100&page=1"
![image](https://github.com/xnl-h4ck3r/waymore/assets/50110633/5b476792-c50f-49cf-aab5-c129fea96065)
Get a url, have a port 4045.
But I use waymore, view result, it doesn't have a port.
![image](https://github.com/xnl-h4ck3r/waymore/assets/50110633/699e1fc9-56c0-4d7f-97f2-ab7060c89028)

**Comment by xnl-h4ck3r** [comment]
Hi @muxueo 
Thanks for raising this issue, I'll look into it. I understand whey you won't share it here, but are you okay messaging me on Twitter with the actual domain you are using so I can see a real example? I understand if you don't want to.
In the returned JSON from otx.alienvault.com, what field is the Port shown in? Is it just in the `url` field?
Thanks
Xnl

**Comment by muxueo** [comment]
Yes, it's a URL field.
I have already sent a message on Twitter

**Comment by muxueo** [comment]
fix in v1.25
