### ISSUE TITLE
results save

### ISSUE THREAD

**Issue by SirKnightV** [xnl-h4ck3r/waymore#30]
Hello, there is a method or option for no save downloaded data?, i just want extract all links but dont want waymore download any data like files images etc but i want waymore only save pure links but without download data

**Comment by xnl-h4ck3r** [comment]
HI @SirKnightV 
You can pass `-mode U` to only get links. The mode can be U (retrieve URLs only), R (download Responses only) or B (Both)
Is that what you were trying to do?
Thanks
Xnl

**Comment by xnl-h4ck3r** [comment]
Hi @SirKnightV. Did my previous response answer your question? Do you still have a problem with waymore, or can I close this issue? Thanks

**Comment by xnl-h4ck3r** [comment]
Hi @SirKnightV. You didn't get back to me, but I'm assuming that you just needed to use `-mode U` to get what you wanted. I will close the issue, but if you still have a problem then feel free to re-open this or open a new one. Thanks
