### ISSUE TITLE
Feature Request [Support for multiple keys in config.yaml file]

### ISSUE THREAD

**Issue by AyushXtha** [xnl-h4ck3r/waymore#31]
It would be really helpful if we can add multiple URLSCAN_API_KEY which will be used at random in config.yaml file separated by commas as I am continuously getting rate-limited. 
Thank you,

**Comment by xnl-h4ck3r** [comment]
Hi @AyushXtha 
I've added it to the TODO list! Thanks for using waymore and raising a suggestion.
Kind regards
Xnl

**Comment by localhost-MouhannadlrX** [comment]
Hi , I hope that also for VirusTotoal apiKeys!

**Comment by xnl-h4ck3r** [comment]
Hi @AyushXtha and @localhost-MouhannadlrX. Not sure if you saw my previous message. As I mentioned, I don't think I will be making this change as explained before, so I will close this issue now. I hope you understand. Thanks
