### ISSUE TITLE
-oU urls.txt flag overwrites the contents of the file if a list of hosts are provided.

### ISSUE THREAD

**Issue by meispi** [xnl-h4ck3r/waymore#32]
when I run `waymore -lcc 3 -mode U hosts.txt -oU urls.txt` the file `urls.txt` is overwritten with the urls of the new host that is in the file. The new URLs should be appended. Can you fix this? or am I making a mistake here?

**Comment by xnl-h4ck3r** [comment]
Hi @meispi. The syntax of what you're running doesm't look quite right. You need to pass the `hosts.txt` with `-i`. I'm not sure it would actually run with what you said so maybe that isn't exactly what you're using?
So it should be `python3 waymore.py -i hosts.txt -mode U -lcc 3 -oU urls.txt` for example. It should not overwite the `urls.txt` file though unless yuou use the `-ow` argument. If it is still happening, can you send me the actual comman you have used? Thanks

**Comment by meispi** [comment]
Apologies for the confusion. I did use the flag `-i`, but somehow missed it while creating this issue.
Command: `waymore -lcc 3 -mode U -i hosts.txt -oU urls.txt`

**Comment by xnl-h4ck3r** [comment]
You're right, it's overwriting the file and it shouldn't be! I'll look into it and try to get a fix sorted soon. Thanks for taking the time to raise the issue

**Comment by xnl-h4ck3r** [comment]
Hey @meispi, I have just released a new verion that should hopefully fix this issue. Let me know if it resolves your problem.
Many thanks
Xnl

**Comment by xnl-h4ck3r** [comment]
Awesome. Thanmks for raising it
