### ISSUE TITLE
Docker legacy builder is deprecated

### ISSUE THREAD

**Issue by malespiaut** [xnl-h4ck3r/waymore#33]
Hello,

When following your instructions and using `docker build` to build `waymore`, I get the following warning message.

```
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/buildx/
```

I don't know how to fix this issue since I'm not a Docker user, I would have made a pull request otherwise.

Best regards.

**Comment by xnl-h4ck3r** [comment]
Hi @malespiaut. Thanks for using waymore and taking the time to raise an issue. Was this message just a warning and it still worked ok for you, or did waymore not work at all because of this? Thanks

**Comment by xnl-h4ck3r** [comment]
Hi @malespiaut. I'm not sure if you saw my previous message. Did the tool still work despite the warning message?

**Comment by xnl-h4ck3r** [comment]
Hi @malespiaut. I was just wondering if you saw my previous messages. Did you get waymore working ok in docker despite that message? Many thanks

**Comment by xnl-h4ck3r** [comment]
Hi. As I got no repsonse to my previous messages, and I believe that waymore still works despite this warning message, I will close this for now. I know it's someting that needs to be addresses at some point, but I don't have the time to look into this, and I personally have never used docker to use waymore (someone else did a PR to run this code). If others use docker and it becomes an issue then I will address it then. Thanks
