### ISSUE TITLE
-oU <file> with multiple domains only saves results from last domain.

### ISSUE THREAD

**Issue by ounissi-zakaria** [xnl-h4ck3r/waymore#35]
## Problem
When running `waymore` with a list of domains and `-oU output-urls.txt`  the tool writes over the previous results and keeps only results from the last domain in the list. 
Example: 
`>waymore -i domains.txt -mode U -oU output-urls.txt`

with `domains.txt`: 
```
google.com
yahoo.com
```

we will only get results for `yahoo.com` in `output-urls.com`

## Possible solution:
I didn't get to reading the code but it can be probably fixed by using `open(output_file,"w+")` instead of `open(output_file,"w")`. I'll try to read it later and maybe make a pr if possible.

**Comment by xnl-h4ck3r** [comment]
Hi @ounissi-zakaria 
Thanks for using the tool and for taking the time to raise an issue. I'll look into fixing this.
Regards
Xnl

**Comment by xnl-h4ck3r** [comment]
Hi @ounissi-zakaria, are you using the latest version of waymore here? I've tried reproducing this, but with smaller domains, but the output file had output from both subs.
Also, note, when you run for google.com, just archive.org alone will need to make 696,427 separate web requests to get all that data! If that is 1 request per second, you're looking at running for 8 days straight!
And yahoo needs 243,688 requests. It tells you this at the start when you ran it.

Maybe you got rate limited and then it stopped so didn't get URLs for google.com in your case? If you use `-v` you can have more idea about what is happening

**Comment by ounissi-zakaria** [comment]
@xnl-h4ck3r Thank you for checking it out. I updated the tool and it's to be wokring as expected now. I should've updated it before raising the issue, sorry. Thank you again for your help

**Comment by xnl-h4ck3r** [comment]
No problem! Just shout if ypou have any other problems, questions or suggestions! :)
