### ISSUE TITLE
waymore freeze sometime

### ISSUE THREAD

**Issue by Kamikaze798** [xnl-h4ck3r/waymore#38]
sometime waymore get stuck when give the tool  time it keep being  still stuck special in this last  phrase:
![Screenshot_2024-02-07_22_41_13](https://github.com/xnl-h4ck3r/waymore/assets/62010613/0274a167-51f3-4444-a9c3-e709dc38875a)

**Comment by xnl-h4ck3r** [comment]
Hi @Kamikaze798, thanks for using the tool and taking the time to raise an issue. Are you passing a file of domains to waymore? What command are you using exactly, and does it stop on the same domain each time?
It is likely that it is just getting rate limited by archive.org and waymore has to wait for a while before continuing. The default wait time when it gets a 429 is 3 minutes (but can be changed with `--wayback-rate-limit-retry`). You can also say how many times it retries after a 429 with `--retires`.
However, the archive.org API is not designed for huge amount of volumes unfortunately, and the default settings are usually ok, but can have problems if you increase `-p` for example. I hope that helps

**Comment by Kamikaze798** [comment]
i pass like this :cat Live_subdomains.txt|waymore -f -xav -xcc -xus -mode U -oU waymore.txt,if i sontimes get the 429 but that not that issue, i guess it is because of large amount  of domains if using the -p then it is all clear ,thank you

**Comment by xnl-h4ck3r** [comment]
Hi @Kamikaze798. The `-p` defaults to 1 anyway, so if you aren't changing it it should be ok. 
One important thing to note... do not pass separate sub domains to waymore unless you really only want data for that subdomain and nothing else. If all the subs in that file are for the same domain, then you are wasting a lot of time passing all those separately. You just need to pass the domain, and you will get results for all subs for that domain. By doing it per subdomain, you are taking so much longer, and have potential of not getting some data if there is a sub that is archived that you don't have in your file. I hope that makes sense

**Comment by Kamikaze798** [comment]
oh get it now just the main domain and you get the rest win a lot of time that's cool idea

**Comment by xnl-h4ck3r** [comment]
Yep. When you pass a domain only, e.g. `tragte.com`, it calls the API's with `*.target.com` so gets all subs. I always do `cat waymore.txt | unfurl domains` after to check if there are any new subdomains I didn't know about

**Comment by Kamikaze798** [comment]
that great ideas respect that .

**Comment by Kamikaze798** [comment]
all the suggestion worked fine thank you for it is create tool hope you continue developing it.
