### ISSUE TITLE
[ 400 ] Unable to get links from urlscan.io

### ISSUE THREAD

**Issue by riramar** [xnl-h4ck3r/waymore#39]
Hi @xnl-h4ck3r 

First, thanks for your tool!
I'm getting the error "[ 400 ] Unable to get links from urlscan.io" even providing a valid API key.
By invoking the https://urlscan.io/api/v1/scan/ with the same key, I can get the results back without any issue.

Regards,
Ricardo Iramar

**Comment by xnl-h4ck3r** [comment]
Hi @riramar. Thanks for using waymore and taking the time to raise an issue. Can you double check the API key is in the correct format in the config file? Can you use the `-v` option and see if there are any more details about Utlscan and the error? Thanks

**Comment by riramar** [comment]
Got the problem from the debug.

`The URLScan URL requested to get links: https://urlscan.io/api/v1/search/?q=domain:www.example.com/&size=10000`

I was passing the URL with a / in the end like https://www.example.com/ and breaking the request. By removing the / in the end it solved the problem. :)

**Comment by riramar** [comment]
Closing since it's not a bug.

**Comment by xnl-h4ck3r** [comment]
Hi @riramar. Thanks for using waymore and taking the time to raise this. Actually, it is something I need to do a change for to stop that error happening. I will remove any trailing / if passed to ensure it still gets results. Many thanks

**Comment by xnl-h4ck3r** [comment]
It's also highlighted a similar issue I need to fix with Alien Vault, so thank you!
