### ISSUE TITLE
get an error zsh killed

### ISSUE THREAD

**Issue by ArslanMazhar** [xnl-h4ck3r/waymore#4]
![IMG_20220703_165155_975](https://user-images.githubusercontent.com/48792133/177038386-819b4fc4-c279-442a-b1f9-0847c242bdb1.jpg)

**Comment by xnl-h4ck3r** [comment]
Hi @ArslanMazhar 
As mentioned on our twitter messages, this is because of lack of memory resources on your machine, so I'm closing this issue now.
Thanks for taking the time to raise the issue, and let me know if you get any other problems.
Many thanks
Xnl
