### ISSUE TITLE
FR: Add setuptools Entry Points Config

### ISSUE THREAD

**Issue by CoreyD97** [xnl-h4ck3r/waymore#40]
First of all, great tool! Though, something I'd like to see is a configuration that allows the tool to be easily called from any directory. I know I can alias the tool or add it to the path, but this FR would hopefully be better for all users.

The tool is already using setuptools, so I don't think too much work would be needed to configure it to have [Entry Points](https://setuptools.pypa.io/en/latest/userguide/entry_point.html). 

Another added bonus is that with this change, the package could be pushed to [PyPI](https://pypi.org/) and therefore easily installed via pip.

**Comment by xnl-h4ck3r** [comment]
Hi @CoreyD97. Thanks, and you're right that would make it much better. I'll try to get this sorted soon

**Comment by xnl-h4ck3r** [comment]
Hi @CoreyD97. v3.0 is now available and you can install with pip using `pip install git+https://github.com/xnl-h4ck3r/waymore.git` (plus other changes). I haven't added that to PyPi yet, but will sort that part later (not really sure how I do that yet, but thought I'd get this bit done).

**Comment by CoreyD97** [comment]
Awesome work dude, you rock!

**Comment by xnl-h4ck3r** [comment]
Thank you!!
