### ISSUE TITLE
Incorrect directory creation by waymore script leading to unexpected output location

### ISSUE THREAD

**Issue by aquilamacedo** [xnl-h4ck3r/waymore#41]
**Description:**

When executing the command `waymore -i lucasfilm.com -mode B` without specifying the output, the output should technically be saved within the path `~/.config/waymore/results/lucasfilm.com`. However, for some reason, the `waymore.py` script is creating a directory with the name `'~'` and saving the files there. Consequently, when running a tree command in the current directory where waymore was executed, it appears as follows:

![image](https://github.com/xnl-h4ck3r/waymore/assets/43859386/c0ab46d8-f4dd-4ff2-a65c-ca580cd324d8)

The `'~'` directory is actually a folder within the current directory where waymore was executed.

**How to Reproduce:**

1. Execute the command: `waymore -i lucasfilm.com -mode B`
2. Observe the directory structure within the current working directory.

**Expected behavior:**

The output files should be saved within the path `~/.config/waymore/results/lucasfilm.com`, not in a directory named `'~'` within the current working directory.

**System information:**

 - OS: Debian GNU/Linux 12 (bookworm)
 - ZSH Version: zsh 5.9 (x86_64-debian-linux-gnu)

**Comment by xnl-h4ck3r** [comment]
Hi @aquilamacedo, thanks for using waymore and taking the time to raise this (and the Pull Request).
I can't actually replicate this myself. The line of cpde in the PR gets executed if there was a previous yellow warning message about the config file. Can you let me know what message you had so I can understand if there is another issue before the line in the PR (which does need changing, so thank you)

**Comment by aquilamacedo** [comment]
You're welcome @xnl-h4ck3r. waymore is a very useful tool.  :-)

Are you referring to the orange message in the screenshot about the `config.yml`?

![image](https://github.com/xnl-h4ck3r/waymore/assets/43859386/c1babb5e-3d5d-4763-82d9-a63b9e8c8e78)

**Comment by xnl-h4ck3r** [comment]
When you install, I don't think it is successfully creating the config.yml file. I assume you don't have `~/.config/waymore/config.yml` on your system then? Where do config files for other tools get written? Are they in a different location, or is that location correct and the setup script is failing to create it for some reason maybe

**Comment by aquilamacedo** [comment]
Exactly, for some reason, waymore is not creating the file `~/.config/waymore/config.yml`. Typically, configuration files for other tools are indeed saved in `~/.config` as well.

**Comment by xnl-h4ck3r** [comment]
Hi @aquilamacedo. Could you do me a favour and delete the waymore config file, and then run `pip install git+https://github.com/xnl-h4ck3r/waymore.git -v` again. Can you look for a green message and let me know what it says?

**Comment by xnl-h4ck3r** [comment]
Hi @aquilamacedo. Could you do me a favour and delete the waymore config file, and then run `pip install git+https://github.com/xnl-h4ck3r/waymore.git -v` again. Can you look for a green message and let me know what it says?

**Comment by aquilamacedo** [comment]
Hi @xnl-h4ck3r. Following this method, it seemingly worked.

![image](https://github.com/xnl-h4ck3r/waymore/assets/43859386/18c23323-bd30-44e8-ac57-d0f8e7a469b8)

The issue is that I was running `python3 setup.py install` using sudo, and the .config was going to the root directory; I didn't pay attention to that, sorry.

**Comment by xnl-h4ck3r** [comment]
Ok, cool. So it's all working as expected? Yeah, it's habit to run `python3 setup.py install` so easy mistake to make! Thanks

**Comment by aquilamacedo** [comment]
Yes, now it seems to be working fine; it has created the `config.yml` :-).

Just to understand, this doesn't invalidate the PR, right? Since if the `config.yml`
doesn't exist for some reason, this problem will occur.

**Comment by xnl-h4ck3r** [comment]
Yes, you are right. The PR is still valid so I will close this and accept the PR. Thank you!
