### ISSUE TITLE
Building wheel for psutil (pyproject.toml) did not run successfully

### ISSUE THREAD

**Issue by noob6t5** [xnl-h4ck3r/waymore#51]
I tried downloading  waymore then I got error while  building wheel for psutil.  
**pip install waymore**

It gave me below error , I tried to run   apt-get install gcc python3-dev. still 
i can't download waymore in Termux.

data/data/com.termux/files/usr/lib -lpython3.11 -o build/lib.linux-armv8l-cpython-311/psutil/_psutil_linux.abi3.so
      clang: error: unknown argument: '-fno-openmp-implicit-rpath'
      clang: error: unknown argument: '-fno-openmp-implicit-rpath'
      psutil could not be installed from sources. Perhaps Python header files are not installed. Try running:
        sudo apt-get install gcc python3-dev
      error: command '/data/data/com.termux/files/usr/bin/arm-linux-androideabi-clang' failed with exit code 1
      [end of output]
![IMG_20240527_125521](https://github.com/xnl-h4ck3r/waymore/assets/67364489/de4bfb3f-6896-42a8-acc8-92755a622c21)

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for psutil
Failed to build psutil
ERROR: Could not build wheels for psutil, which is required to install pyproject.toml-based projects

**Comment by xnl-h4ck3r** [comment]
Hi @le3tCoder , could you try running `python3 -m pip install --upgrade pip` first and then try installing waymore again?

**Comment by le3tCoder** [comment]
I tried that before 🥲 
Is this problem with Termux Packages with pip?
![IMG_20240527_173828](https://github.com/xnl-h4ck3r/waymore/assets/67364489/67817e84-2016-4337-ad5f-b47affab7fce)
![IMG_20240527_173735](https://github.com/xnl-h4ck3r/waymore/assets/67364489/f0184ebc-2152-4194-8f7f-9e39e40ab9e3)
![IMG_20240527_173713](https://github.com/xnl-h4ck3r/waymore/assets/67364489/029a8064-385b-463c-a124-88f2cae0fc9d)

**Comment by xnl-h4ck3r** [comment]
You may have tried already, but can you run `sudo apt update && sudo apt upgrade -y` and see if that helps?

**Comment by le3tCoder** [comment]
Sudo doesn't work in termux unless your device is root

**Comment by le3tCoder** [comment]
yes, 
for sudo device needs to be rooted,

I will seek for a way if i found something i will share here 
thank you for your kind support

**Comment by xnl-h4ck3r** [comment]
Sorry I'm not more helpful with this problem! Just wondering, do you get a simialr probem with any tool you install with pip, or just mine?

**Comment by le3tCoder** [comment]
I have successfully installed tool's like arjun xsstrike .
I'm sorry to say but for now it's only problem with waymore

**Comment by xnl-h4ck3r** [comment]
Sorry about that. Does it happen with my other tools too? If you run `pip install xnLinkFinder` do you get the same issue?

**Comment by le3tCoder** [comment]
Yes bro 

![IMG_20240528_075403](https://github.com/xnl-h4ck3r/waymore/assets/67364489/54116cdc-e113-46c0-9c79-dc2188c55f59)

**Comment by le3tCoder** [comment]
yes bro. i think it's problem with psutil , in your code.

**Comment by mswell** [comment]
Hi @le3tCoder, what is the version of your termux ?

![image](https://github.com/xnl-h4ck3r/waymore/assets/2567185/af838d8c-d047-4b30-b540-cf5e7fe3cc90)

**Comment by damnvuln** [comment]
I am really sorry for late reply . 
The version of termux that i am using is **1.42.1** downloaded from F-droid . 

Does it Work's in new version @mswell ?? ,

**Comment by SAKIB-SALIM** [comment]
> Yes bro
> 
> ![IMG_20240528_075403](https://private-user-images.githubusercontent.com/67364489/334246040-54116cdc-e113-46c0-9c79-dc2188c55f59.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MzY5NTAsIm5iZiI6MTcyODczNjY1MCwicGF0aCI6Ii82NzM2NDQ4OS8zMzQyNDYwNDAtNTQxMTZjZGMtZTExMy00NmMwLTljNzktZGMyMTg4YzU1ZjU5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDEyMzczMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4NWIwNmM5N2VhZTkzNzRhZmMwNTIyYTEwZjEzMTY2NTU5NGY2YmNhNTcxNWQzMGVkNGIyNjVkZDNmZTFmZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KZA6u-VFby-ocDKZz4rGJ2-V04_s8o43GRGvtWMgqgs)

You don't have necessary package installed. Run
`apt install libxml2 libxslt`
Or you can install python package `libxml2` with apt
`apt install python-lxml`

**Comment by SAKIB-SALIM** [comment]
> I tried downloading waymore then I got error while building wheel for psutil. **pip install waymore**
> 
> It gave me below error , I tried to run apt-get install gcc python3-dev. still i can't download waymore in Termux.
> 
> data/data/com.termux/files/usr/lib -lpython3.11 -o build/lib.linux-armv8l-cpython-311/psutil/_psutil_linux.abi3.so clang: error: unknown argument: '-fno-openmp-implicit-rpath' clang: error: unknown argument: '-fno-openmp-implicit-rpath' psutil could not be installed from sources. Perhaps Python header files are not installed. Try running: sudo apt-get install gcc python3-dev error: command '/data/data/com.termux/files/usr/bin/arm-linux-androideabi-clang' failed with exit code 1 [end of output] ![IMG_20240527_125521](https://private-user-images.githubusercontent.com/67364489/334001827-de4bfb3f-6896-42a8-acc8-92755a622c21.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MzcyOTIsIm5iZiI6MTcyODczNjk5MiwicGF0aCI6Ii82NzM2NDQ4OS8zMzQwMDE4MjctZGU0YmZiM2YtNjg5Ni00MmE4LWFjYzgtOTI3NTVhNjIyYzIxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDEyNDMxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyYmZmMmFkMDZkNGE0ZGU4ZGU5ODFjNDk2MWNiYzU0N2E2YmY3NTNhZDM3OWM1OWI2NGE0ZmVlMjNkZTg0MzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JvtRfUIKJ3WCSUrJx4SN44FrGQjA6F38AW6VW5Azzb8)
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for psutil Failed to build psutil ERROR: Could not build wheels for psutil, which is required to install pyproject.toml-based projects

Try reinstalling clang and python.
I think you delete some headers from your termux instance.

**Comment by noob6t5** [comment]
I tried everything still not working/

Can you confirm from your side that it's working?

**Comment by SAKIB-SALIM** [comment]
Yes, it's working from my side. On a fresh instead. Can you check if you have clang/gcc installed?

**Comment by noob6t5** [comment]
gcc is replaced by libllvm , 
I tried everything .

pip install psutil
apt-get install libllvm
apt install python-lxml

still psutil isn't working .. I think the problem is with termux package so i already opened PR for it 

But tool like arjun is installing

**Comment by SAKIB-SALIM** [comment]
Install clang

**Comment by noob6t5** [comment]
i have installed it , still not working.
can u provide me your termux version?
It's not working for me 
![Screenshot_2024-10-19-18-50-18-212_com termux](https://github.com/user-attachments/assets/b595e654-069d-4af1-affc-f141209c78af)

**Comment by noob6t5** [comment]
It worked...... 
 Thanks!!
