### ISSUE TITLE
[ ERR ] unable to get links from archive.org: 

### ISSUE THREAD

**Issue by Shuvamoy** [xnl-h4ck3r/waymore#52]
When I run a scan, I get the below error for archive.org

[ ERR ] unable to get links from archive.org:

**Comment by xnl-h4ck3r** [comment]
Hi @Shuvamoy. I need a bit more information to try and help you. Can you double check that you can actually access the web archive from the machine you are running waymore on, and also that  the archive actually has any links for that domain, e.g. run `curl -s "https://web.archive.org/cdx/search/cdx?url=*.YOURDOMAIN.COM/"` and check you get results.

**Comment by adhvaidhloi** [comment]
i am also facing the same issue

**Comment by xnl-h4ck3r** [comment]
Hi @adhvaidhloi. Can you also double check that you can actually access the web archive from the machine you are running waymore on, and also that the archive actually has any links for that domain, e.g. run curl -s "https://web.archive.org/cdx/search/cdx?url=*.YOURDOMAIN.COM/*" and check you get results.

**Comment by adhvaidhloi** [comment]
hey @xnl-h4ck3r thank you for your reply. I fixed the issue  using chatgpt.

**Comment by xnl-h4ck3r** [comment]
Hi @adhvaidhloi, that's great! Can you please share what the problem actually was and how you fixed it please, to help others with the same issue? Thanks

**Comment by adhvaidhloi** [comment]
Hey @xnl-h4ck3r  sorry for the late reply i used "pip install waymore --upgrade" this command to fix my issue.
