### ISSUE TITLE
No value for "URLSCAN_API_KEY" in config.yml 

### ISSUE THREAD

**Issue by chirag9718** [xnl-h4ck3r/waymore#53]
i have already provided api keys what to do to solve this problem

**Comment by xnl-h4ck3r** [comment]
Hi @chirag9718 . Can you check that the config file has a space between `URLSCAN_API_KEY:` and your api key, and the key isn't in quotes or anything?
If that is correct, can you also run waymore with `-v` so you can see the path of the config file waymore is using, just in case you have more than one for some reason and it's looking at the wrong one?

**Comment by xnl-h4ck3r** [comment]
Hi @chirag9718 , I am closing this now because I haven't seen a problem myself or had anyone else report. I assume it was just a mistake when you added to the config file. If I am wrong and you still have a problem, then feel free to reopen this issue. Thanks
