### ISSUE TITLE
Discord WEBHOOK ISSUE

### ISSUE THREAD

**Issue by rabiu-101** [xnl-h4ck3r/waymore#56]
Hi 

I am getting this "ERROR notifyDiscord 1: can only concatenate str (not "NoneType") to str"

**Comment by xnl-h4ck3r** [comment]
Hi @rabiu-101. Sorry for the delay in replying. Is this still an issue, or did you manage to resolve it? Was the discord webhook set correctly in the config file (e.g. `WEBHOOK_DISCORD: https://discord.com/api/webhooks/xxxxxxxxxxxxxxxxxxxxxx`)?

**Comment by xnl-h4ck3r** [comment]
Do you mean you just aren't tryng to send to a discord webhook now?
Does the `WEBHOOK_DISCORD:` key have a value in your config file?

**Comment by xnl-h4ck3r** [comment]
Sorry, not sure by your message whether you resolved your issue or if there is still a problem? Thanks
