### ISSUE TITLE
Common Crawl connection error for index

### ISSUE THREAD

**Issue by mohaned2210** [xnl-h4ck3r/waymore#57]
![image](https://github.com/user-attachments/assets/e0f8328a-ead1-4699-9070-a62f617b6fd5)
![image](https://github.com/user-attachments/assets/461553e9-04b9-45a6-8a8d-1e4ec99679a8)
take a long time then said Common Crawl connection error for index

**Comment by mohaned2210** [comment]
I suggest setting an option that enables you to skip the unresponsive source when the tool is always running, because sometimes some sources may not respond and sometimes respond, it helps in solving automation problems.

**Comment by xnl-h4ck3r** [comment]
Hi @mohaned2210. As mentioned in the README, Common Crawl can take a very long because there are over 95 separate indexes that it searches, and their API is also poorly performing. The error is for 1 index out of all of those that times out for some reason. 
Because of ongoing issues with Common Crawl is so bad, I personally only check that single latest index instead of all of them, To do that I use `-lcc 1`. Hope that helps

**Comment by mohaned2210** [comment]
Ok thanks for responding I will try it

**Comment by xnl-h4ck3r** [comment]
Hi @mohaned2210. Sorry, I made a mistake there, by defaul;t it only looks at the latest 3 indexes and they now have 100 or more. The main site that the list if indexes and each index is retrieved from is https://index.commoncrawl.org/ 
If you look at that right now, there seems to be a problem with it and shows no indexes. The list of indexes should be on https://index.commoncrawl.org/collinfo.json but I get a secure connection failed error on that so something is very broken on their system.

However, it really shouldn't take as long as it does to time out when running waymore, so I am re-opening this and will try to see if there is anything I can do.
Thanks
Xnl

**Comment by xnl-h4ck3r** [comment]
I would probably recommend using `-xcc` to exlcude Common Crawl altogether for now to be honest!

**Comment by xnl-h4ck3r** [comment]
I have made these changes in v4.6 to imporve where I can:
- The default value for how many CC indexes to check will be 1 instead of 3
- The retyr strategy will be a lot lower so won't spend as long trying to get the data
Update by running `pip install --upgrade waymore`
Thanks

**Comment by mohaned2210** [comment]
Good to hear that Thank you
