### ISSUE TITLE
URLScan rate limit reached

### ISSUE THREAD

**Issue by molitona** [xnl-h4ck3r/waymore#9]
Hi, urlscan always doesn't succeed to fetch all links, can it be resolved ?

[ 429 ] URLScan rate limit reached, so stopping. Links that have already been retrieved will be saved.

**Comment by xnl-h4ck3r** [comment]
Hi @molitona 
I thought I'd added it to the help, but I can't see it now... you  can sign up to urlscan.io for a free subscription and get an API Key form them. You can add that into `config.yml` like `URLSCAN_API_KEY: <your_key>`. This will allow you to get more back and quicker, but they will still rate limit you. Unless you pay for their top tier subscription then they are going to purposely rate limit you. At least the free API key can get a bit more back before they do limit oyu though.
I'll get the README changed to include info about the API Key.
Thanks
Xnl

**Comment by molitona** [comment]
thank you <3

**Comment by Azathothas** [comment]
Hi @xnl-h4ck3r , is there a way to specify **_multiple_** `URLSCAN_API_KEY` in `config.yaml` ?

**Comment by xnl-h4ck3r** [comment]
> Hi @xnl-h4ck3r , is there a way to specify **_multiple_** `URLSCAN_API_KEY` in `config.yaml` ?

Not at the moment sorry
